def palabras():
    palabra_secreta = [
        'cuerpo',
        'pierna',
        'pie',
        'rodilla',
        'muslo',
        'cabeza',
        'cara',
        'boca',
        'labio',
        'diente',
        # 'ojo',
        # 'nariz',
        # 'barba',
        # 'bigote',
        # 'cabello',
        # 'oreja',
        # 'cerebro',
        # 'estómago',
        # 'brazo',
        # 'codo',
        # 'hombro',
        # 'uña',
        # 'mano',
        # 'muñeca',
        # 'palma',
        # 'dedo',
        # 'abdomen',
        # 'cuello',
        # 'mente',
        # 'alma',
        # 'espíritu',
        # 'pecho',
        # 'cintura',
        # 'cadera',
        # 'espalda',
        # 'sangre',
        # 'carne',
        # 'piel',
        # 'hueso',
        # 'resfriado',
        # 'gripe',
        # 'salud',
        # 'enfermedad',
        # 'humanidad',
        # 'humano',
        # 'persona',
        # 'gente',
        # 'hombre',
        # 'mujer',
        # 'niño',
        # 'niña',
        # 'adolescente',
        # 'adulto',
        # 'adulta',
        # 'anciano',
        # 'anciana',
        # 'señor',
        # 'señora',
        # 'caballero',
        # 'dama'
    ]


def significado_palabra_secreta():
    significados = [
        'Conjunto de las partes que forman un ser vivo.',
        'Extremidad inferior del cuerpo humano, que va desde el tronco hasta el pie',
        'Parte del cuerpo humano que va desde el tobillo hasta la punta de los dedos',
        'Articulación del cuerpo humano que une el fémur con la tibia, y partes blandas que la rodean.',
        'Parte de la pierna humana que va desde la cadera hasta la rodilla.',
        'Parte superior del cuerpo del hombre',
        'Parte anterior de la cabeza del hombre y de algunos animales.',
        'Abertura corporal por la que se ingieren alimento',
        'Parte exterior carnosa y movible de la parte inferior del rostro',
        'Pieza ósea dura y blanca que crece, junto con otras, en la boca del hombre'
    ]
